#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


SCRIPT_DIR = Path(__file__).resolve().parent
TYPEDB_ROOT = SCRIPT_DIR.parent
FRAGMENTS_ROOT = TYPEDB_ROOT / "schema" / "fragments"
DEFAULT_OUTPUT = TYPEDB_ROOT / "schema" / "str-ontology.tql"
DEFAULT_DOMAIN_JSON = TYPEDB_ROOT / "inventory_latest" / "domain_inventory_latest.json"

SECTION_ORDER = [
    ("kernel", FRAGMENTS_ROOT / "00-kernel"),
    ("as_is", FRAGMENTS_ROOT / "10-as-is"),
    ("to_be", FRAGMENTS_ROOT / "20-to-be"),
    ("bridges", FRAGMENTS_ROOT / "30-bridges"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build canonical TypeDB schema from TQL fragments")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Canonical generated schema path")
    parser.add_argument(
        "--domain-json",
        type=Path,
        default=DEFAULT_DOMAIN_JSON,
        help="Optional JSON sidecar produced by domain-inventory for generated # @toon values injection",
    )
    return parser.parse_args()


def read_section(dir_path: Path) -> list[str]:
    if not dir_path.exists():
        return [f"# (missing directory: {dir_path})"]

    files = sorted(p for p in dir_path.glob("*.tql") if p.is_file())
    if not files:
        return [f"# (no fragments in {dir_path.name})"]

    lines: list[str] = []
    for fragment in files:
        text = fragment.read_text(encoding="utf-8").strip()
        fragment_tag = fragment.stem.split("-", 1)[-1]
        lines.append(f"# --- <{dir_path.name[3:]}.{fragment_tag}> ---")
        if text:
            lines.extend(text.splitlines())
        else:
            lines.append("# (empty fragment)")
        lines.append(f"# --- </{dir_path.name[3:]}.{fragment_tag}> ---")
        lines.append("")
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def load_domain_inventory(path: Path) -> dict[str, dict] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_priority_display(value: str) -> str:
    compact = re.sub(r"[^A-Z0-9]+", "", value.upper())
    if compact == "UNKNOWN":
        return "UNKNOWN"
    match = re.fullmatch(r"P?([1-7])", compact)
    if not match:
        return value
    return f"P{match.group(1)}"


def render_toon_values(attr: str | dict, inventory: dict[str, dict] | None) -> str | None:
    if isinstance(attr, dict):
        attr = str(attr.get("id"))
    if not inventory:
        return None
    payload = inventory.get(attr)
    if not payload:
        return None
    values = payload.get("values") or []
    declared_domain = payload.get("declared_domain")
    max_values = payload.get("max_values") or 0
    if declared_domain == "structured":
        return "# @toon values: <structured domain; see domain_inventory_latest.md>"
    if len(values) == 0:
        return None
    if max_values and len(values) > int(max_values):
        return "# @toon values: <too many values; see domain_inventory_latest.md>"

    normalized: list[str] = []
    seen: set[str] = set()
    for value in values:
        display = str(value).strip('"').strip()
        if attr == "priority":
            display = normalize_priority_display(display)
        if display in seen:
            continue
        seen.add(display)
        normalized.append(display)
    normalized.sort(key=lambda value: (value != "null", value.casefold()))
    return "# @toon values: " + " | ".join(normalized)


def inject_toon_values(schema_text: str, inventory: dict[str, dict] | None) -> str:
    if not inventory:
        return schema_text
    lines = schema_text.splitlines()
    out: list[str] = []
    for line in lines:
        out.append(line)
        stripped = line.strip()
        if stripped.startswith("attribute "):
            attr_name = stripped.split()[1].rstrip(",")
            values_line = render_toon_values(attr_name, inventory)
            if values_line:
                out.append(values_line)
                out.append("")
    return "\n".join(out).rstrip() + "\n"


def build_schema_text(domain_inventory: dict[str, dict] | None = None) -> str:
    out: list[str] = [
        "define",
        "",
        "# Generated from ontology/typedb/schema/fragments/*.tql",
        "# Do not edit this file manually; edit TQL fragments and regenerate.",
        "",
    ]
    for section_name, section_dir in SECTION_ORDER:
        out.append(f"# --- <{section_name}> ---")
        out.extend(read_section(section_dir))
        out.append(f"# --- </{section_name}> ---")
        out.append("")
    text = "\n".join(out).rstrip() + "\n"
    return inject_toon_values(text, domain_inventory)


def build_outputs(domain_inventory: dict[str, dict] | None = None) -> tuple[dict, str]:
    payload = {
        "generated_from": "ontology/typedb/schema/fragments/*.tql",
        "sections": ["kernel", "as_is", "to_be", "bridges"],
    }
    return payload, build_schema_text(domain_inventory)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    args = parse_args()
    domain_inventory = load_domain_inventory(args.domain_json)
    schema_text = build_schema_text(domain_inventory)
    write_text(args.output, schema_text)
    print(f"[build-typedb-schema] wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
