#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from typedb_ontology_toon import (
    FRAGMENT_SECTION_ORDER,
    emit_yaml,
    load_toon_fragment,
    render_inventory_comments,
    render_semantic_card_comments,
    sort_inventory_values,
    validate_toon_fragment,
)

TYPEDB_ROOT = SCRIPT_DIR.parent
SCHEMA_ROOT = TYPEDB_ROOT / "schema"
FRAGMENTS_ROOT = SCHEMA_ROOT / "fragments"
DEFAULT_TQL_OUTPUT = SCHEMA_ROOT / "str-ontology.tql"
DEFAULT_YAML_OUTPUT = SCHEMA_ROOT / "str-ontology.yaml"
DEFAULT_DOMAIN_JSON = TYPEDB_ROOT / "inventory_latest" / "domain_inventory_latest.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build canonical TOON aggregate and TypeDB schema from TOON fragments")
    parser.add_argument("--tql-output", type=Path, default=DEFAULT_TQL_OUTPUT)
    parser.add_argument("--yaml-output", type=Path, default=DEFAULT_YAML_OUTPUT)
    parser.add_argument("--domain-json", type=Path, default=DEFAULT_DOMAIN_JSON)
    return parser.parse_args()


def load_domain_inventory(path: Path) -> dict[str, dict] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def render_toon_values(card: dict, inventory: dict[str, dict] | None) -> str | None:
    if not inventory:
        return None
    payload = inventory.get(card["id"])
    if not payload:
        return None
    values = payload.get("values") or []
    declared_domain = payload.get("declared_domain")
    max_values = payload.get("max_values") or 0
    if declared_domain == "structured":
        return "# @toon values: <structured domain; see domain_inventory_latest.md>"
    if not values:
        return None
    if max_values and len(values) > int(max_values):
        return "# @toon values: <too many values; see domain_inventory_latest.md>"
    return "# @toon values: " + " | ".join(sort_inventory_values(values))


def load_sections() -> list[dict]:
    section_payloads: list[dict] = []
    errors: list[str] = []
    for section in FRAGMENT_SECTION_ORDER:
        section_dir = FRAGMENTS_ROOT / section
        fragments: list[dict] = []
        for fragment_path in sorted(section_dir.glob("*.toon.yaml")):
            payload = load_toon_fragment(fragment_path)
            errors.extend(validate_toon_fragment(payload, fragment_path))
            fragments.append(payload)
        section_payloads.append({"name": section.split("-", 1)[-1].replace("-", "_"), "fragments": fragments})
    if errors:
        raise ValueError("\n".join(errors))
    return section_payloads


def build_tql(section_payloads: list[dict], inventory: dict[str, dict] | None) -> str:
    out = [
        "define",
        "",
        "# Generated from ontology/typedb/schema/fragments/*.toon.yaml",
        "# Do not edit this file manually; edit TOON fragments and regenerate.",
        "",
    ]
    seen_attribute_ids: set[str] = set()
    for section in section_payloads:
        section_name = section["name"]
        out.append(f"# --- <{section_name}> ---")
        for fragment in section["fragments"]:
            out.append(f"# --- <{section_name}.{fragment['fragment']}> ---")
            for card in fragment["cards"]:
                target = card["target"]
                tql_block = str(card["tql"]).rstrip()
                if target == "attribute":
                    if card["id"] in seen_attribute_ids:
                        continue
                    seen_attribute_ids.add(card["id"])
                    for line in render_inventory_comments(card):
                        out.append(line)
                    out.extend(tql_block.splitlines())
                    values_line = render_toon_values(card, inventory)
                    if values_line:
                        out.append(values_line)
                        out.append("")
                else:
                    out.extend(render_semantic_card_comments(card))
                    out.extend(tql_block.splitlines())
                if out[-1] != "":
                    out.append("")
            if out[-1] == "":
                out.pop()
            out.append(f"# --- </{section_name}.{fragment['fragment']}> ---")
            out.append("")
        if out[-1] == "":
            out.pop()
        out.append(f"# --- </{section_name}> ---")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def build_outputs(inventory: dict[str, dict] | None = None) -> tuple[dict, str]:
    sections = load_sections()
    aggregate = {
        "version": 1,
        "generated_from": "ontology/typedb/schema/fragments/*.toon.yaml",
        "sections": sections,
    }
    return aggregate, build_tql(sections, inventory)


def build_schema_text(domain_inventory: dict[str, dict] | None = None) -> str:
    return build_tql(load_sections(), domain_inventory)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    args = parse_args()
    inventory = load_domain_inventory(args.domain_json)
    aggregate, tql_text = build_outputs(inventory)
    yaml_text = emit_yaml(aggregate)
    write_text(args.yaml_output, yaml_text)
    write_text(args.tql_output, tql_text)
    print(f"[build-typedb-schema] wrote {args.yaml_output}")
    print(f"[build-typedb-schema] wrote {args.tql_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
