export const COLLECTIONS = {
  CLIENTS: 'clients',
  PROJECTS: 'projects',
  PROJECT_RATES: 'project_rates',
  EMPLOYEES: 'employees',
  EMPLOYEE_MONTH_COST: 'employee_month_cost',
  TIMESHEETS_MONTHLY: 'timesheets_monthly',
  FACTS_PROJECT_MONTH: 'facts_project_month',
  FORECAST_VERSIONS: 'forecast_versions',
  FORECASTS_PROJECT_MONTH: 'forecasts_project_month',
  FX_MONTHLY: 'fx_monthly',
  PERIODS: 'periods',
  ATTACHMENTS: 'attachments',
  ENTITY_ATTACHMENTS: 'entity_attachments',
  AUDIT_EVENTS: 'audit_events',
  AGENT_REQUESTS: 'agent_requests',
  ALERT_SETTINGS: 'alert_settings',
  FUND_COMMENTS: 'fund_comments',
} as const;
