const constants = {
    notion_ticket_statuses: {
        NONE: 'No Status',
        PLANNED: 'Planned',
        READY_TO_GO: 'Ready to go',
        IN_PROGRESS: 'In Progress',
        REVIEW: 'Review',
        AGREEMENT: 'Agreement',
        DONE: 'Done 🙌',
        ARCHIVE: 'Archive',
    },
    notion_ticket_types: [
        'Research',
        'Concept',
        'Low Res',
        'Hi Res',
        'Design',
        'UX flow',
        'Visual',
        'Fixes',
        'Doc',
        'Presentation',
        'Refactoring',
        'DesignSystem',
        'Other',
        'CJM',
        'JBTD',
        'Develop',
        'Prototype',
    ],
    action_sheets: {
        TICKET_MENU: 'TICKET_MENU',
        CHANGE_STATUS: 'CHANGE_STATUS',
        TRACK_TIME: 'TRACK_TIME',
        REJECT_TICKET: 'REJECT_TICKET',
    },
    notion_ticket_priorities: ['🔥 P1 ', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7'],
    task_statuses: {
        DRAFT_10: 'Draft',
        READY_10: 'Ready',
        PROGRESS_10: 'Progress 10',
        REVIEW_10: 'Review / Ready',
        DONE_10: 'Done',
        ARCHIVE: 'Archive',
    },
    simplified_crm_statuses: {
        Draft: 'Draft',
        Ready: 'Ready',
        'Progress 10': 'In Progress',
        'Review / Ready': 'Review',
        Done: 'Done',
        Archive: 'Archive',
    },
    performer_crm_statuses: {
        Draft: 'DRAFT_10',
        Ready: 'READY_10',
        'In Progress': 'PROGRESS_10',
        Review: 'REVIEW_10',
        Done: 'DONE_10',
        Archive: 'ARCHIVE',
    },
    crm_to_notion_statuses: {
        Draft: 'No Status',
        Ready: 'Ready to go',
        'Progress 10': 'In Progress',
        'Review / Ready': 'Review',
        'Done': 'Done 🙌',
        Archive: 'Archive',
    },
    notion_to_crm_statuses: {
        'No Status': 'Draft',
        'Ready to go': 'Ready',
        'In Progress': 'Progress 10',
        Review: 'Review / Ready',
        'Done 🙌': 'Done',
        Archive: 'Archive',
    },
} as const;

export default constants;
