const constants = {
    notion_ticket_statuses: {
        NONE: 'No Status',
        PLANNED: 'Planned',
        READY_TO_GO: 'Ready to go',
        IN_PROGRESS: 'In Progress',
        REVIEW: 'Review',
        AGREEMENT: 'Agreement',
        DONE: 'Done 🙌',
        ARCHIVE: 'Archive',
    },
    notion_ticket_types: [
        'Research',
        'Concept',
        'Low Res',
        'Hi Res',
        'Design',
        'UX flow',
        'Visual',
        'Fixes',
        'Doc',
        'Presentation',
        'Refactoring',
        'DesignSystem',
        'Other',
        'CJM',
        'JBTD',
        'Develop',
        'Prototype',
    ],
    action_sheets: {
        TICKET_MENU: 'TICKET_MENU',
        CHANGE_STATUS: 'CHANGE_STATUS',
        TRACK_TIME: 'TRACK_TIME',
        REJECT_TICKET: 'REJECT_TICKET',
    },
    notion_ticket_priorities: ['🔥 P1 ', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7'],
    task_statuses: {
        NEW_0: 'Backlog',
        NEW_10: 'New / Request',
        NEW_20: 'New / Clientask',
        NEW_30: 'New / Detail',
        NEW_40: 'New / Readyforplan',
        PLANNED_10: 'Plan / Approval',
        PLANNED_20: 'Plan / Performer',
        READY_10: 'Ready',
        PROGRESS_0: 'Rejected',
        PROGRESS_10: 'Progress 10',
        PROGRESS_20: 'Progress 25',
        PROGRESS_30: 'Progress 50',
        PROGRESS_40: 'Progress 90',
        REVIEW_10: 'Review / Ready',
        REVIEW_20: 'Review / Implement',
        AGREEMENT_10: 'Upload / Deadline',
        AGREEMENT_20: 'Upload / Delivery',
        DONE_10: 'Done',
        DONE_20: 'Complete',
        DONE_30: 'PostWork',
        ARCHIVE: 'Archive',
        PERIODIC: 'Periodic',
    },
    simplified_crm_statuses: {
        Backlog: 'New',
        'New / Request': 'New',
        'New / Clientask': 'New',
        'New / Detail': 'New',
        'New / Readyforplan': 'New',
        Rejected: 'New',
        'Plan / Approval': 'Planned',
        'Plan / Performer': 'Planned',
        Ready: 'Ready',
        'Progress 10': 'In Progress',
        'Progress 25': 'In Progress',
        'Progress 50': 'In Progress',
        'Progress 90': 'In Progress',
        'Review / Ready': 'Review',
        'Review / Implement': 'Review',
        'Upload / Deadline': 'Agreement',
        'Upload / Delivery': 'Agreement',
        Done: 'Done',
        Complete: 'Done',
        PostWork: 'Done',
        Archive: 'Archive',
        Periodic: 'Periodic',
    },
    performer_crm_statuses: {
        Ready: 'Ready',
        'In Progress': 'Progress 10',
        Review: 'Review / Ready',
    },
    crm_to_notion_statuses: {
        Backlog: 'No Status',
        'New / Request': 'No Status',
        'New / Clientask': 'No Status',
        'New / Detail': 'No Status',
        'New / Readyforplan': 'No Status',
        Rejected: 'No Status',
        'Plan / Approval': 'Planned',
        'Plan / Performer': 'Planned',
        Ready: 'Ready to go',
        'Progress 10': 'In Progress',
        'Progress 25': 'In Progress',
        'Progress 50': 'In Progress',
        'Progress 90': 'In Progress',
        'Review / Ready': 'Review',
        'Review / Implement': 'Review',
        'Upload / Deadline': 'Agreement',
        'Upload / Delivery': 'Agreement',
        'Done': 'Done 🙌',
        'Complete': 'Done 🙌',
        'PostWork': 'Done 🙌',
        Archive: 'Archive',
    },
    notion_to_crm_statuses: {
        'No Status': 'New / Request',
        Planned: 'Plan / Approval',
        'Ready to go': 'Ready',
        'In Progress': 'Progress 10',
        Review: 'Review / Ready',
        Agreement: 'Upload / Deadline',
        'Done 🙌': 'Complete',
        Archive: 'Archive',
    },
} as const;

export default constants;
