export const LEGACY_TASK_STATUS_VALUES = {
  NEW_0: 'Legacy / Backlog',
  NEW_10: 'New / Request',
  NEW_20: 'New / Clientask',
  NEW_30: 'New / Detail',
  NEW_40: 'New / Readyforplan',
  PLANNED_10: 'Plan / Approval',
  PLANNED_20: 'Plan / Performer',
  BACKLOG_10: 'Backlog',
  PROGRESS_0: 'Rejected',
  PROGRESS_20: 'Progress 25',
  PROGRESS_30: 'Progress 50',
  PROGRESS_40: 'Progress 90',
  REVIEW_20: 'Review / Implement',
  AGREEMENT_10: 'Upload / Deadline',
  AGREEMENT_20: 'Upload / Delivery',
  DONE_20: 'Complete',
  DONE_30: 'PostWork',
  PERIODIC: 'Periodic',
} as const;

export const LEGACY_TASK_SURFACE_SOURCE_STATUSES = [
  LEGACY_TASK_STATUS_VALUES.NEW_0,
  LEGACY_TASK_STATUS_VALUES.NEW_10,
  LEGACY_TASK_STATUS_VALUES.NEW_20,
  LEGACY_TASK_STATUS_VALUES.NEW_30,
  LEGACY_TASK_STATUS_VALUES.NEW_40,
  LEGACY_TASK_STATUS_VALUES.PLANNED_10,
  LEGACY_TASK_STATUS_VALUES.PLANNED_20,
  LEGACY_TASK_STATUS_VALUES.BACKLOG_10,
  LEGACY_TASK_STATUS_VALUES.PROGRESS_0,
  LEGACY_TASK_STATUS_VALUES.PROGRESS_20,
  LEGACY_TASK_STATUS_VALUES.PROGRESS_30,
  LEGACY_TASK_STATUS_VALUES.PROGRESS_40,
  LEGACY_TASK_STATUS_VALUES.REVIEW_20,
  LEGACY_TASK_STATUS_VALUES.AGREEMENT_10,
  LEGACY_TASK_STATUS_VALUES.AGREEMENT_20,
  LEGACY_TASK_STATUS_VALUES.DONE_20,
  LEGACY_TASK_STATUS_VALUES.DONE_30,
  LEGACY_TASK_STATUS_VALUES.PERIODIC,
] as const;

export const LEGACY_VOICE_DRAFT_SOURCE_STATUSES = [
  LEGACY_TASK_STATUS_VALUES.BACKLOG_10,
  LEGACY_TASK_STATUS_VALUES.NEW_0,
] as const;

export const LEGACY_VOICE_ACCEPTED_SOURCE_STATUSES = [
  LEGACY_TASK_STATUS_VALUES.BACKLOG_10,
] as const;

export const LEGACY_SOFT_DELETED_REPAIR_SOURCE_STATUSES = [
  LEGACY_TASK_STATUS_VALUES.NEW_0,
  LEGACY_TASK_STATUS_VALUES.BACKLOG_10,
  'Ready',
  'Draft',
] as const;

export const isLegacyPeriodicTaskStatus = (value: unknown): boolean =>
  typeof value === 'string' && value.trim() === LEGACY_TASK_STATUS_VALUES.PERIODIC;
